version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: database_
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - /etc/mongo/mongo-new.keyfile:/etc/mongo/mongodb-keyfile:ro
    command: ["mongod", "--bind_ip_all", "--auth", "--replSet", "rs0", "--keyFile", "/etc/mongo/mongodb-keyfile"]
    restart: on-failure
    networks:
      - tomatesoft_network

  mongo-init:
    image: node:18
    container_name: mongo_init_rs
    depends_on:
      - database
    volumes:
      - ./mongo-init:/app
    working_dir: /app
    entrypoint: sh -c "sleep 10 && node init-replica.js"
    networks:
      - tomatesoft_network

  backend:
    ...
  frontend:
    ...

volumes:
  mongodb_data:

networks:
  tomatesoft_network:
    driver: bridge
