version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: database_
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - /etc/mongo/mongo-new.keyfile:/etc/mongo/mongodb-keyfile:ro
    command: ["mongod", "--bind_ip_all", "--auth", "--replSet", "rs0", "--keyFile", "/etc/mongo/mongodb-keyfile"]
    restart: on-failure
    networks:
      - tomatesoft_network

  backend:
    image: tomatesoft_server:latest
    container_name: backend_
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - tomatesoft_network
    ports:
      - "${SERVER_PORTS}"

  frontend:
    image: tomatesoft_frontend:latest
    container_name: frontend_
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - tomatesoft_network

volumes:
  mongodb_data:
    driver: local

networks:
  tomatesoft_network:
    driver: bridge
