export enum State {
  ACTIVE = 'ACTIVE',
  CONFLICT = 'CONFLICT',
  CLOSED = 'CLOSED',
  APPROVED = 'APPROVED',
}
export enum Processing {
  INITIAL = 'INITIAL',
  CONFIRM_PROCESSING = 'CONFIRM_PROCESSING',
  SHOW_TILL_DETAILS = 'SHOW_TILL_DETAILS',
}
